### ISSUE TITLE
Probabile problema nella documentazione nell'installazione di un nuovo nodo validatore TESTNET 3.0

### ISSUE THREAD

**Issue by angeloderricohestro** [commercionetwork/commercio-consortium#5]
Sto installando, un nodo validatore nuovo con la TESTNET 3.0 seguendo il documento:

**https://github.com/commercionetwork/commercio-consortium/tree/upgrade-from-v2-to-v3/testnet/11k**

Nel passaggio della documentazione dove afferma:

> Init the .commercionetwork folder with the basic configuration:
> 
> **commercionetworkd unsafe-reset-all
> commercionetworkd init $NODENAME**
> 
> Install genesis.json file:
> 
> **rm -rf ~/.commercionetwork/config/genesis.json
> cp genesis.json ~/.commercionetwork/config**

Nell'eseguire il comando **cp genesis.json...**, non posso procedere in quanto il file non è presente.

Attendo un cortese cenno di risposta.

**Comment by marcotradenet** [comment]
Il problema si verifica molto probabilmente se si è usciti dal server e poi rientrati: a quel punto ci si trova nella home del proprio utente e non nel path `$HOME/commercio-chains/commercio-testnet11k`.    
Potete confermare che è successo questo?

**Comment by angeloderricohestro** [comment]
No, ho eseguito i passaggi nella stessa sessione.

**Comment by marcotradenet** [comment]
Nella cartella `$HOME/commercio-chains/commercio-testnet11k` quindi non c'è il file?

**Comment by angeloderricohestro** [comment]
La cartella non è presente.

Riparto da zero con un nuovo nodo e aggiorno la issue.

**Comment by marcotradenet** [comment]
Prima di questi due comandi
```bash
rm -rf ~/.commercionetwork/config/genesis.json
cp genesis.json ~/.commercionetwork/config
```

Prova a usare il comando `pwd` per capire dove ti trovi

**Comment by angeloderricohestro** [comment]
/home/commercionetwork/commercio-chains/commercio-testnet11k

Qui il file c'è...

**Comment by marcotradenet** [comment]
> /home/commercionetwork/commercio-chains/commercio-testnet11k
> 
> Qui il file c'è...

E' la stessa posizione di prima e il file `genesis.json` c'è. Non è chiaro come mai prima non c'era.      
Possiamo provare a usare solo path assoluti usando variabili tipo `$HOME`, ma non è sicuro che poi il problema si risolva: il path `/home/commercionetwork/commercio-chains/commercio-testnet11k` dovrebbe essere uguale a `$HOME/commercio-chains/commercio-testnet11k`  ma sembra che sul tuo sistema sia diverso.     

In ogni caso il concetto è che il file da usare come genesis è presente qui 

https://github.com/commercionetwork/chains/blob/commercio-testnet11k/commercio-testnet11k/genesis.json

Alternativamente si può pensare di usare un comando 
```bash
curl https://raw.githubusercontent.com/commercionetwork/chains/commercio-testnet11k/commercio-testnet11k/genesis.json > \
~/.commercionetwork/config/genesis.json
```

**Comment by angeloderricohestro** [comment]
Dunque... Ripartendo e seguendo sempre la documentazione, il FULL NODE INSTALLATION è COMPLETATA.

Domani, 20/02, effettuo la parte di BECAME VALIDATOR.

**Comment by marcotradenet** [comment]
> Dunque... Ripartendo e seguendo sempre la documentazione, il FULL NODE INSTALLATION è COMPLETATA.
> 
> Domani, 20/02, effettuo la parte di BECAME VALIDATOR.

La issue si può chiudere quindi, oppure pensi che si possa aggiungere qualche indicazione alla documentazione?

**Comment by angeloderricohestro** [comment]
Dire di no, sembra OK. Possiamo chiudere la issue.
