### ISSUE TITLE
BECAME VALIDATOR: Delega fallita

### ISSUE THREAD

**Issue by angeloderricohestro** [commercionetwork/commercio-consortium#6]
Nel documento al link:

### https://github.com/commercionetwork/commercio-consortium/blob/upgrade-from-v2-to-v3/testnet/11k/becoming-validator.md

eseguo nell'ordine:

1. commercionetworkd keys add $NODENAME -> OK
2. commercionetworkd query bank balances <your pub addr creator val> --chain-id $CHAINID -> Mi dice che non ho token e allora eseguo: https://faucet-testnet.commercio.network/give?addr=your_pub_addr_creator_val&amount=10000 -> OK: la risposta che ottengo è la seguente:

> balances:
> - amount: "10000"
>   denom: ucommercio
> pagination:
>   next_key: null
>   total: "0"

3. export VALIDATOR_PUBKEY=$(commercionetworkd tendermint show-validator) -> OK
4. commercionetworkd tx staking create-validator \
  --amount=10000ucommercio \
  --pubkey=$VALIDATOR_PUBKEY \
  --moniker="$NODENAME" \
  --chain-id="$CHAINID" \
  --identity="" \
  --website="" \
  --details="" \
  --commission-rate="0.10" \
  --commission-max-rate="0.20" \
  --commission-max-change-rate="0.01" \
  --min-self-delegation="1" \
  --from=<your pub addr creator val> \
  --fees=10000ucommercio \
  -y (con i dati richiesti correttamente valorizzati) -> NOK: il messaggio che ottengo è il seguente:

> {"height":"5222356","txhash":"1C5E0715EE8D78E742C51084965A4B7F79A10BB13E9CBC7257D83C9AAB875603","codespace":"sdk","code":5,"data":"","raw_log":"failed to execute message; message index: 0: failed to delegate; 0ucommercio is smaller than 10000ucommercio: insufficient funds","logs":[],"info":"","gas_wanted":"200000","gas_used":"118157","tx":null,"timestamp":""}

Attendo indicazioni. 

Grazie.

**Comment by marcotradenet** [comment]
Le istruzioni sono state aggiornate.

**Comment by angeloderricohestro** [comment]
Possiamo chiudere questa issue.
