### ISSUE TITLE
BECAME VALIDATOR: Link alla dashboard della TESTNET non corretto

### ISSUE THREAD

**Issue by angeloderricohestro** [commercionetwork/commercio-consortium#7]
Nel documento:

**https://github.com/commercionetwork/commercio-consortium/blob/upgrade-from-v2-to-v3/testnet/11k/becoming-validator.md**

Il link riportato come:

**Commercio.network explorer Testnet** che risponde a: **https://testnet.commercio.network/it/validators** da come risultato 404.

**Comment by marcotradenet** [comment]
Il link è stato corretto

**Comment by angeloderricohestro** [comment]
OK. Chiudo la issue.
