### ISSUE TITLE
BECOME VALIDATOR: Non è chiaro dove si ottiene <your pub addr delegator>

### ISSUE THREAD

**Issue by angeloderricohestro** [commercionetwork/commercio-consortium#8]
Nel documento:

https://github.com/commercionetwork/commercio-consortium/blob/upgrade-from-v2-to-v3/testnet/11k/becoming-validator.md

Laddove è indicato <your pub addr delegator> non è chiaro dove lo si ottiene.

Attendo informazioni per procedere con la procedura.

Grazie infinite.

**Comment by marcotradenet** [comment]
Non è indicato perché non lo si ottiene da nessuna parte: è il wallet con la maggior parte dei token, ma lo si può creare attraverso il faucet oppure al limite lo si richiede.    
Sulla testnet non è necessario versare 50000 token.

**Comment by angeloderricohestro** [comment]
Quindi? Cosa dovrei inserire?

**Comment by angeloderricohestro** [comment]
Non riesco ad eseguire il comando che segue, prossimo alla conclusione:

> commercionetworkd tx staking delegate \
>   $OPERATOR_ADDRESS \
>    [amount of tokens]ucommercio \
>   --from <your pub addr delegator> \
>   --chain-id="$CHAINID" \
>   --fees=10000ucommercio \
>   -y

Ma gli **[amount of tokens]** da dove li prendo?

**Comment by marcotradenet** [comment]
> Quindi? Cosa dovrei inserire?

Puoi creare un wallet e farti dare i token dal faucet e poi usare quello per fare la delega. L'amount può essere anche di 1ucommercio.  

All'inizio del paragrafo riguardante la delega, comunque, c'è scritto **If you want**: non è una condizione necessaria quella di fare una delega per creare un validatore

**Comment by angeloderricohestro** [comment]
Infatti, non l'ho fatto... avere come nodo validatore 1.00000xxxx token mi sembra bassissimo.

**Comment by marcotradenet** [comment]
> Infatti, non l'ho fatto... avere come nodo validatore 1.00000xxxx token mi sembra bassissimo.

Stiamo parlando di testnet: non serve che ci siano migliaia di token delegati. Se ci sono necessità a riguardo particolari dovranno essere richieste espressamente.

**Comment by angeloderricohestro** [comment]
Perfetto! Possiamo chiudere la issue.
